---
# Connect into VM
- name: Wait for connection
  wait_for:
    host: "{{ item.openstack.public_v4 }}"
    port: 22
    timeout: 120
    search_regex: OpenSSH
  loop: "{{ os_instance.results }}"

# Add ipv4 address of remote VMs into inventory
- name: Adding hosts to inventory
  add_host:
    name: " {{ item.openstack.name }}"
    groups: mrc_ssh
    ansible_ssh_host: "{{ item.openstack.public_v4 }}"
  loop: '{{ os_instance.results }}'