- name: Deploy MRC instances
  hosts: localhost
  vars:
    ansible_python_interpreter: auto
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- name: DEBUG - remove instances
  hosts: localhost

  roles:
    - role: debug-rm-instance