# Provision VM instance(s) on MRC
- name: Deploy MRC instances
  hosts: localhost
  vars_files: "host_vars/mrc.yaml"

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

# Open SSH into the provisioned VM(s)
- name: Open SSH connecton into VM(s)
  hosts: localhost

  roles:
    - role: instance-connection

# Setup VM instances based on usage
- name: Configure VM instances
  hosts: mrc_ssh
  become: yes

  roles:
    - role: instance-internet-access
    - role: openstack-common


# TODO run VM scripts

# - name: DEBUG - remove instances
#   hosts: localhost

#   roles:
#     - role: debug-rm-instance