---

# Install WebApp dependencies
- name: Install dependencies
  become: yes
  apt:
    name: ['nodejs', 'npm']
    force_apt_get: yes
    state: present

# Clone github repo
- name: Clone git repo
  git:
    repo: https://github.com/voltun/COMP90024-S1-2021-A2.git
    dest: ~/github
    update: yes