---
# Create an instance on NeCTAR
- name: Create CouchDB and Harvester instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volumes }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  when: 'not (item.name| regex_search(".*WebApp.*"))'
  loop: '{{ instances }}'
  register: os_instance

# Create an instance on NeCTAR
- name: Create WebApp instances
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_webapp_flavor }}'
    availability_zone: '{{ availability_zone }}'
    security_groups: '{{ sg_names }}'
    volumes: '{{ item.volumes }}'
    auto_floating_ip: yes
    wait: yes
    timeout: 600
    state: present
  when: 'item.name| regex_search(".*WebApp.*")'
  loop: '{{ instances }}'
  register: webapp_instance

# Change facts if WebApp created
- name: Update facts
  set_fact:
    os_instance: '{{ webapp_instance }}'
  when: webapp_instance.changed

